import requests
from bs4 import BeautifulSoup

weaponChoices = [
  { "name": "Dull Blade", "value": "11101" },
  { "name": "Silver Sword", "value": "11201" },
  { "name": "Cool Steel", "value": "11301" },
  { "name": "Harbinger of Dawn", "value": "11302" },
  { "name": "Traveler's Handy Sword", "value": "11303" },
  { "name": "Dark Iron Sword", "value": "11304" },
  { "name": "Fillet Blade", "value": "11305" },
  { "name": "Skyrider Sword", "value": "11306" },
  { "name": "Favonius Sword", "value": "11401" },
  { "name": "The Flute", "value": "11402" },
  { "name": "Sacrificial Sword", "value": "11403" },
  { "name": "Royal Longsword", "value": "11404" },
  { "name": "Lion's Roar", "value": "11405" },
  { "name": "Prototype Rancour", "value": "11406" },
  { "name": "Iron Sting", "value": "11407" },
  { "name": "Blackcliff Longsword", "value": "11408" },
  { "name": "The Black Sword", "value": "11409" },
  { "name": "The Alley Flash", "value": "11410" },
  { "name": "Sword of Descension", "value": "11412" },
  { "name": "Festering Desire", "value": "11413" },
  { "name": "Amenoma Kageuchi", "value": "11414" },
  { "name": "Cinnabar Spindle", "value": "11415" },
  { "name": "Kagotsurube Isshin", "value": "11416" },
  { "name": "Sapwood Blade", "value": "11417" },
  { "name": "Xiphos' Moonlight", "value": "11418" },
  { "name": "Prized Isshin Blade", "value": "11419" },
  { "name": "Prized Isshin Blade", "value": "11420" },
  { "name": "Prized Isshin Blade", "value": "11421" },
  { "name": "Toukabou Shigure", "value": "11422" },
  { "name": "Aquila Favonia", "value": "11501" },
  { "name": "Skyward Blade", "value": "11502" },
  { "name": "Freedom-Sworn", "value": "11503" },
  { "name": "Summit Shaper", "value": "11504" },
  { "name": "Primordial Jade Cutter", "value": "11505" },
  { "name": "Primordial Jade Cutter", "value": "11506" },
  { "name": "One Side", "value": "11507" },
  { "name": "Mistsplitter Reforged", "value": "11509" },
  { "name": "Haran Geppaku Futsu", "value": "11510" },
  { "name": "Key of Khaj-Nisut", "value": "11511" },
  { "name": "Light of Foliar Incision", "value": "11512" },
  { "name": "Waster Greatsword", "value": "12101" },
  { "name": "Old Merc's Pal", "value": "12201" },
  { "name": "Ferrous Shadow", "value": "12301" },
  { "name": "Bloodtainted Greatsword", "value": "12302" },
  { "name": "White Iron Greatsword", "value": "12303" },
  { "name": "Quartz", "value": "12304" },
  { "name": "Debate Club", "value": "12305" },
  { "name": "Skyrider Greatsword", "value": "12306" },
  { "name": "Favonius Greatsword", "value": "12401" },
  { "name": "The Bell", "value": "12402" },
  { "name": "Sacrificial Greatsword", "value": "12403" },
  { "name": "Royal Greatsword", "value": "12404" },
  { "name": "Rainslasher", "value": "12405" },
  { "name": "Prototype Archaic", "value": "12406" },
  { "name": "Whiteblind", "value": "12407" },
  { "name": "Blackcliff Slasher", "value": "12408" },
  { "name": "Serpent Spine", "value": "12409" },
  { "name": "Lithic Blade", "value": "12410" },
  { "name": "Snow-Tombed Starsilver", "value": "12411" },
  { "name": "Luxurious Sea-Lord", "value": "12412" },
  { "name": "Katsuragikiri Nagamasa", "value": "12414" },
  { "name": "Makhaira Aquamarine", "value": "12415" },
  { "name": "Akuoumaru", "value": "12416" },
  { "name": "Forest Regalia", "value": "12417" },
  { "name": "Skyward Pride", "value": "12501" },
  { "name": "Wolf's Gravestone", "value": "12502" },
  { "name": "Song of Broken Pines", "value": "12503" },
  { "name": "The Unforged", "value": "12504" },
  { "name": "Primordial Jade Greatsword", "value": "12505" },
  { "name": "The Other Side", "value": "12506" },
  { "name": "Redhorn Stonethresher", "value": "12510" },
  { "name": "Beginner's Protector", "value": "13101" },
  { "name": "Iron Point", "value": "13201" },
  { "name": "White Tassel", "value": "13301" },
  { "name": "Halberd", "value": "13302" },
  { "name": "Black Tassel", "value": "13303" },
  { "name": "The Flagstaff", "value": "13304" },
  { "name": "Dragon's Bane", "value": "13401" },
  { "name": "Prototype Starglitter", "value": "13402" },
  { "name": "Crescent Pike", "value": "13403" },
  { "name": "Blackcliff Pole", "value": "13404" },
  { "name": "Deathmatch", "value": "13405" },
  { "name": "Lithic Spear", "value": "13406" },
  { "name": "Favonius Lance", "value": "13407" },
  { "name": "Royal Spear", "value": "13408" },
  { "name": "Dragonspine Spear", "value": "13409" },
  { "name": "Kitain Cross Spear", "value": "13414" },
  { "name": "The Catch", "value": "13415" },
  { "name": "Wavebreaker's Fin", "value": "13416" },
  { "name": "Moonpiercer", "value": "13417" },
  { "name": "Missive Windspear", "value": "13419" },
  { "name": "Staff of Homa", "value": "13501" },
  { "name": "Skyward Spine", "value": "13502" },
  { "name": "Vortex Vanquisher", "value": "13504" },
  { "name": "Primordial Jade Winged-Spear", "value": "13505" },
  { "name": "Deicide", "value": "13506" },
  { "name": "Calamity Queller", "value": "13507" },
  { "name": "Engulfing Lightning", "value": "13509" },
  { "name": "Staff of the Scarlet Sands", "value": "13511" },
  { "name": "Apprentice's Notes", "value": "14101" },
  { "name": "Pocket Grimoire", "value": "14201" },
  { "name": "Magic Guide", "value": "14301" },
  { "name": "Thrilling Tales of Dragon Slayers", "value": "14302" },
  { "name": "Otherworldly Story", "value": "14303" },
  { "name": "Emerald Orb", "value": "14304" },
  { "name": "Twin Nephrite", "value": "14305" },
  { "name": "Amber Bead", "value": "14306" },
  { "name": "Favonius Codex", "value": "14401" },
  { "name": "The Widsith", "value": "14402" },
  { "name": "Sacrificial Fragments", "value": "14403" },
  { "name": "Royal Grimoire", "value": "14404" },
  { "name": "Solar Pearl", "value": "14405" },
  { "name": "Prototype Amber", "value": "14406" },
  { "name": "Mappa Mare", "value": "14407" },
  { "name": "Blackcliff Agate", "value": "14408" },
  { "name": "Eye of Perception", "value": "14409" },
  { "name": "Wine and Song", "value": "14410" },
  { "name": "Frostbearer", "value": "14412" },
  { "name": "Dodoco Tales", "value": "14413" },
  { "name": "Hakushin Ring", "value": "14414" },
  { "name": "Oathsworn Eye", "value": "14415" },
  { "name": "Wandering Evenstar", "value": "14416" },
  { "name": "Fruit of Fulfillment", "value": "14417" },
  { "name": "Skyward Atlas", "value": "14501" },
  { "name": "Lost Prayer to the Sacred Winds", "value": "14502" },
  { "name": "Lost Ballade", "value": "14503" },
  { "name": "Memory of Dust", "value": "14504" },
  { "name": "Primordial Jade Regalia", "value": "14505" },
  { "name": "Everlasting Moonglow", "value": "14506" },
  { "name": "Kagura's Verity", "value": "14509" },
  { "name": "A Thousand Floating Dreams", "value": "14511" },
  { "name": "Tulaytullah's Remembrance", "value": "14512" },
  { "name": "Hunter's Bow", "value": "15101" },
  { "name": "Seasoned Hunter's Bow", "value": "15201" },
  { "name": "Raven Bow", "value": "15301" },
  { "name": "Sharpshooter's Oath", "value": "15302" },
  { "name": "Recurve Bow", "value": "15303" },
  { "name": "Slingshot", "value": "15304" },
  { "name": "Messenger", "value": "15305" },
  { "name": "Ebony Bow", "value": "15306" },
  { "name": "Favonius Warbow", "value": "15401" },
  { "name": "The Stringless", "value": "15402" },
  { "name": "Sacrificial Bow", "value": "15403" },
  { "name": "Royal Bow", "value": "15404" },
  { "name": "Rust", "value": "15405" },
  { "name": "Prototype Crescent", "value": "15406" },
  { "name": "Compound Bow", "value": "15407" },
  { "name": "Blackcliff Warbow", "value": "15408" },
  { "name": "The Viridescent Hunt", "value": "15409" },
  { "name": "Alley Hunter", "value": "15410" },
  { "name": "Fading Twilight", "value": "15411" },
  { "name": "Mitternachts Waltz", "value": "15412" },
  { "name": "Windblume Ode", "value": "15413" },
  { "name": "Hamayumi", "value": "15414" },
  { "name": "Predator", "value": "15415" },
  { "name": "Mouun's Moon", "value": "15416" },
  { "name": "King's Squire", "value": "15417" },
  { "name": "End of the Line", "value": "15418" },
  { "name": "Skyward Harp", "value": "15501" },
  { "name": "Amos' Bow", "value": "15502" },
  { "name": "Elegy for the End", "value": "15503" },
  { "name": "Kunwu's Wyrmbane", "value": "15504" },
  { "name": "Primordial Jade Vista", "value": "15505" },
  { "name": "Mirror Breaker", "value": "15506" },
  { "name": "Polar Star", "value": "15507" },
  { "name": "Aqua Simulacra", "value": "15508" },
  { "name": "Thundering Pulse", "value": "15509" },
  { "name": "Hunter's Path", "value": "15511" }
]

def scrape_other_languages(url, name, value):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    spans = soup.find_all('span', {'lang': 'vi'})
    if len(spans) != 0:
        if spans[0].string == None:
          print({ "name": "{} ({})".format(name, spans[0].text) , "value": value }, ",")
        else:
          print({ "name": "{} ({})".format(name, spans[0].string) , "value": value }, ",")
    

for weapon in weaponChoices:
    name = weapon["name"]
    value = weapon["value"]
    url = 'https://genshin-impact.fandom.com/wiki/{}'.format(name.replace("'", "%27").replace(" ", "_"))
    scrape_other_languages(url, name, value)