'use strict';

const weaponChoices = [
	{name: 'Dull Blade (Vô Phong Kiếm)', value: '11101'},
	{name: 'Silver Sword (Kiếm Bạc)', value: '11201'},
	{name: 'Cool Steel (Lãnh Nhẫn)', value: '11301'},
	{
		name: 'Harbinger of Dawn (Thần Kiếm Lê Minh)',
		value: '11302',
	},
	{name: "Traveler's Handy Sword (Kiếm Lữ Hành)", value: '11303'},
	{name: 'Dark Iron Sword (Kiếm Sắt Đen)', value: '11304'},
	{name: 'Fillet Blade (Đao Săn Cá)', value: '11305'},
	{name: 'Skyrider Sword (Kiếm Phi Thiên)', value: '11306'},
	{name: 'Favonius Sword (Tây Phong Kiếm)', value: '11401'},
	{name: 'The Flute (Kiếm Sáo)', value: '11402'},
	{name: 'Sacrificial Sword (Kiếm Tế Lễ)', value: '11403'},
	{name: 'Royal Longsword (Trường Kiếm Tông Thất)', value: '11404'},
	{name: "Lion's Roar (Tiếng Hét Của Rồng", value: '11405'},
	{name: 'Prototype Rancour (Mẫu Trảm Nham)', value: '11406'},
	{name: 'Iron Sting (Thiết Phong Kích)', value: '11407'},
	{
		name: 'Blackcliff Longsword (Hắc Nham Trường Kiếm)',
		value: '11408',
	},
	{name: 'The Black Sword (Kiếm Đen)', value: '11409'},
	{name: 'The Alley Flash (Tia Sáng Nơi Hẻm Tối)', value: '11410'},
	{
		name: 'Sword of Descension (Kiếm Giáng Lâm)',
		value: '11412',
	},
	{name: 'Festering Desire (Răng Nanh Rỉ Sét)', value: '11413'},
	{name: 'Amenoma Kageuchi (Đoản Đao Amenoma)', value: '11414'},
	{name: 'Cinnabar Spindle (Con Thoi Chu Sa)', value: '11415'},
	{name: 'Sapwood Blade (Kiếm Gỗ)', value: '11417'},
	{name: "Xiphos' Moonlight (Ánh Trăng Xiphos)", value: '11418'},
	{
		name: 'Toukabou Shigure (Kinh Dị – Một Chân Dưới Màn Mưa)',
		value: '11422',
	},
	{name: 'Aquila Favonia (Phong Ưng Kiếm)', value: '11501'},
	{name: 'Skyward Blade (Thiên Không Kiếm)', value: '11502'},
	{name: 'Freedom-Sworn (Lời Thề Tự Do Cổ Xưa)', value: '11503'},
	{name: 'Summit Shaper (Kiếm Chước Phong)', value: '11504'},
	{
		name: 'Primordial Jade Cutter (Bàn Nham Kết Lục)',
		value: '11505',
	},
	{
		name: 'Primordial Jade Cutter (Bàn Nham Kết Lục)',
		value: '11506',
	},
	{name: 'Mistsplitter Reforged (Ánh Sáng Đêm Sương Mù)', value: '11509'},
	{name: 'Haran Geppaku Futsu (Bạch Nhẫn Lưu Chuyển)', value: '11510'},
	{name: 'Key of Khaj-Nisut (Chìa Khóa Khaj-Nisut)', value: '11511'},
	{name: 'Light of Foliar Incision (Ánh Lá Phán Quyết)', value: '11512'},
	{
		name: 'Waster Greatsword (Kiếm Huấn Luyện)',
		value: '12101',
	},
	{name: "Old Merc's Pal (Kiếm Dụng Binh)", value: '12201'},
	{name: 'Ferrous Shadow (Kiếm Thiết Ảnh)', value: '12301'},
	{name: 'Bloodtainted Greatsword (Kiếm Huyết Rồng)', value: '12302'},
	{name: 'White Iron Greatsword (Kiếm Bạch Thiết)', value: '12303'},
	{name: 'Debate Club (Gậy Thu Phục)', value: '12305'},
	{name: 'Skyrider Greatsword (Đại Kiếm Phi Thiên)', value: '12306'},
	{name: 'Favonius Greatsword (Đại Kiếm Tây Phong)', value: '12401'},
	{name: 'The Bell (Kiếm Chuông)', value: '12402'},
	{name: 'Sacrificial Greatsword (Đại Kiếm Tế Lễ)', value: '12403'},
	{name: 'Royal Greatsword (Đại Kiếm Tông Thất)', value: '12404'},
	{name: 'Rainslasher (Vũ Tài)', value: '12405'},
	{name: 'Prototype Archaic (Mẫu Cổ Hoa)', value: '12406'},
	{name: 'Whiteblind (Kiếm Bạch Ảnh)', value: '12407'},
	{
		name: 'Blackcliff Slasher (Hắc Nham Trảm Đao)',
		value: '12408',
	},
	{name: 'Serpent Spine (Kiếm Li Cốt)', value: '12409'},
	{name: 'Lithic Blade (Thiên Nham Cổ Kiếm)', value: '12410'},
	{name: 'Snow-Tombed Starsilver (Tuyết Vùi Tinh Ngân)', value: '12411'},
	{name: 'Luxurious Sea-Lord (Vua Biển Hàng Hiệu)', value: '12412'},
	{name: 'Katsuragikiri Nagamasa (Trường Đao Katsuragi)', value: '12414'},
	{name: 'Makhaira Aquamarine (Sắc Nước Makhaira)', value: '12415'},
	{name: 'Akuoumaru (Kẻ Cưỡi Sóng Watatsumi)', value: '12416'},
	{name: 'Forest Regalia (Vương Khí Rừng Sâu)', value: '12417'},
	{name: 'Skyward Pride (Thiên Không Kiêu Ngạo)', value: '12501'},
	{name: "Wolf's Gravestone (Đường Cùng Của Sói)", value: '12502'},
	{
		name: 'Song of Broken Pines (Tiếng Gió Trong Rừng Thông)',
		value: '12503',
	},
	{name: 'The Unforged (Kiếm Vô Công)', value: '12504'},
	{
		name: 'Redhorn Stonethresher (Xích Giác Phá Thạch Đao)',
		value: '12510',
	},
	{name: "Beginner's Protector (Thương Tân Thủ)", value: '13101'},
	{name: 'Iron Point (Thương Sắt)', value: '13201'},
	{name: 'White Tassel (Thương Bạch Anh)', value: '13301'},
	{name: 'Halberd (Thuẫn Kích)', value: '13302'},
	{name: 'Black Tassel (Hắc Anh Thương)', value: '13303'},
	{name: "Dragon's Bane (Tai Ương Của Rồng)", value: '13401'},
	{name: 'Prototype Starglitter (Mẫu Tinh Liêm)', value: '13402'},
	{name: 'Crescent Pike (Lưu Nguyệt Châm)', value: '13403'},
	{name: 'Blackcliff Pole (Thương Hắc Nham)', value: '13404'},
	{name: 'Deathmatch (Thương Quyết Chiến)', value: '13405'},
	{name: 'Lithic Spear (Thương Thiên Nham)', value: '13406'},
	{name: 'Favonius Lance (Thương Tây Phong)', value: '13407'},
	{name: 'Royal Spear (Thương Săn Tông Thất)', value: '13408'},
	{name: 'Dragonspine Spear (Thương Long Tích)', value: '13409'},
	{name: 'Kitain Cross Spear (Giáo Thập Tự Kitain)', value: '13414'},
	{name: 'The Catch (Lao Xiên Cá)', value: '13415'},
	{name: "Wavebreaker's Fin (Vây Cá Chẻ Sóng)", value: '13416'},
	{
		name: 'Moonpiercer (Quán Nguyệt Thương)',
		value: '13417',
	},
	{name: 'Missive Windspear (Mũi Nhọn Của Gió)', value: '13419'},
	{name: 'Staff of Homa (Trượng Hộ Ma)', value: '13501'},
	{name: 'Skyward Spine (Xương Sống Thiên Không)', value: '13502'},
	{name: 'Vortex Vanquisher (Giáo Nịnh Thần)', value: '13504'},
	{
		name: 'Primordial Jade Winged-Spear (Hòa Phác Diên)',
		value: '13505',
	},
	{name: 'Calamity Queller (Hủy Diệt)', value: '13507'},
	{name: 'Engulfing Lightning (Đoạn Thảo Trường Đao)', value: '13509'},
	{name: 'Staff of the Scarlet Sands (Quyền Trượng Cát Đỏ)', value: '13511'},
	{name: "Apprentice's Notes (Nhật Ký Học Sinh)", value: '14101'},
	{name: 'Pocket Grimoire (Sổ Tay Ma Pháp)', value: '14201'},
	{name: 'Magic Guide (Tóm Tắt Ma Pháp)', value: '14301'},
	{
		name: 'Thrilling Tales of Dragon Slayers (Câu Chuyện Diệt Rồng)',
		value: '14302',
	},
	{name: 'Otherworldly Story (Tiểu Thuyết Dị Giới)', value: '14303'},
	{name: 'Emerald Orb (Quả Cầu Ngọc)', value: '14304'},
	{name: 'Twin Nephrite (Ngọc Sinh Đôi)', value: '14305'},
	{
		name: 'Favonius Codex (Tây Phong Mật Điển)',
		value: '14401',
	},
	{name: 'The Widsith (Chương Nhạc Lang Thang)', value: '14402'},
	{name: 'Sacrificial Fragments (Mảnh Chương Tế Lễ)', value: '14403'},
	{name: 'Royal Grimoire (Mật Pháp Tông Thất)', value: '14404'},
	{name: 'Solar Pearl (Nhật Nguyệt Hạp)', value: '14405'},
	{name: 'Prototype Amber (Mẫu Kim Phách)', value: '14406'},
	{name: 'Mappa Mare (Hải Đồ Vạn Quốc)', value: '14407'},
	{
		name: 'Blackcliff Agate (Hắc Nham Phỉ Ngọc)',
		value: '14408',
	},
	{name: 'Eye of Perception (Chiêu Tâm)', value: '14409'},
	{name: 'Wine and Song (Rượu Và Thơ Nơi Hẻm Tối)', value: '14410'},
	{name: 'Frostbearer (Trái Chịu Lạnh)', value: '14412'},
	{
		name: 'Dodoco Tales (Tuyển tập các câu chuyện về Dodoco)',
		value: '14413',
	},
	{name: 'Hakushin Ring (Vòng Bạch Thần)', value: '14414'},
	{name: 'Oathsworn Eye (Con Ngươi Tuyên Thệ)', value: '14415'},
	{name: 'Wandering Evenstar (Sao Đêm Rong Ruổi)', value: '14416'},
	{name: 'Fruit of Fulfillment (Quả Mọng)', value: '14417'},
	{name: 'Skyward Atlas (Quyển Thiên Không)', value: '14501'},
	{
		name: 'Lost Prayer to the Sacred Winds (Điển Tích Tây Phong)',
		value: '14502',
	},
	{name: 'Memory of Dust (Khóa Trần Thế)', value: '14504'},
	{name: 'Primordial Jade Regalia (Ngọc Bích Huy Hoàng)', value: '14505'},
	{name: 'Everlasting Moonglow (Vầng Trăng Bất Diệt)', value: '14506'},
	{name: "Kagura's Verity (Chân Ý Của Kagura)", value: '14509'},
	{name: 'A Thousand Floating Dreams (Cõi Mộng Ngàn Đêm)', value: '14511'},
	{name: "Tulaytullah's Remembrance (Hồi Ức Tulaytullah)", value: '14512'},
	{name: "Hunter's Bow (Cung Săn Bắn)", value: '15101'},
	{name: "Seasoned Hunter's Bow (Cung Săn Bắn Tôi Luyện)", value: '15201'},
	{name: 'Raven Bow (Cung Lông Quạ)', value: '15301'},
	{name: "Sharpshooter's Oath (Lời Thề Xạ Thủ Thần)", value: '15302'},
	{name: 'Recurve Bow (Cung Phản Khúc)', value: '15303'},
	{name: 'Slingshot (Nỏ Kéo)', value: '15304'},
	{name: 'Messenger (Tín Sứ)', value: '15305'},
	{name: 'Favonius Warbow (Cung Tây Phong)', value: '15401'},
	{name: 'The Stringless (Tuyệt Huyền)', value: '15402'},
	{name: 'Sacrificial Bow (Cung Tế Lễ)', value: '15403'},
	{name: 'Royal Bow (Trường Cung Tông Thất)', value: '15404'},
	{name: 'Rust (Cung Rỉ Sét)', value: '15405'},
	{name: 'Prototype Crescent (Mẫu Đạm Nguyệt)', value: '15406'},
	{name: 'Compound Bow (Cung Thép)', value: '15407'},
	{
		name: 'Blackcliff Warbow (Cung Hắc Nham)',
		value: '15408',
	},
	{name: 'The Viridescent Hunt (Cung Sắc Xanh)', value: '15409'},
	{name: 'Alley Hunter (Thợ Săn Hẻm Tối)', value: '15410'},
	{name: 'Fading Twilight (Lạc Hà)', value: '15411'},
	{name: 'Mitternachts Waltz (Điệu Van Ban Đêm)', value: '15412'},
	{name: 'Windblume Ode (Bài Ca Hoa Gió)', value: '15413'},
	{name: 'Hamayumi (Cung Trừ Ma)', value: '15414'},
	{name: 'Predator (Kẻ Săn Mồi)', value: '15415'},
	{name: "Mouun's Moon (Ánh Trăng Mouun)", value: '15416'},
	{name: "King's Squire (Cận Vệ Nhà Vua)", value: '15417'},
	{name: 'End of the Line (Sông Cạn)', value: '15418'},
	{name: 'Skyward Harp (Cánh Thiên Không)', value: '15501'},
	{name: "Amos' Bow (Cung Amos)", value: '15502'},
	{name: 'Elegy for the End (Tiếng Thở Dài Vô Tận)', value: '15503'},
	{name: 'Polar Star (Ngôi Sao Cực Đông)', value: '15507'},
	{name: 'Aqua Simulacra (Nhược Thủy)', value: '15508'},
	{name: 'Thundering Pulse (Sấm Sét Rung Động)', value: '15509'},
	{name: "Hunter's Path (Con Đường Thợ Săn)", value: '15511'},
];

const weap1 = '15507';
const weap2 = undefined;

const weapon =
	weaponChoices.filter((e) => e.name === weap1 || e.name === weap2) ??
	weaponChoices.filter((e) => e.value === weap1 || e.value === weap2);

console.log(weapon);
